name: Daily Webtoon Crawler
on:
  schedule:
    # 한국 시간 매일 오후 10시는 UTC 기준 13시입니다.
    - cron: '0 13 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Crawler
      env:
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: python crawler.py
    - name: Commit database
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add webtoons.db
        git diff --quiet && git diff --staged --quiet || git commit -m "Update webtoon database"
        git push