name: Daily Webtoon Crawler

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Crawler to create/update database
      env:
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
      run: python crawler.py

    - name: Commit and Push database
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        # -f 옵션으로 .gitignore를 무시하고 강제로 추가
        git add -f webtoons.db
        # 변경 사항이 있을 때만 커밋
        if ! git diff --staged --quiet; then
          git commit -m "Update webtoon database"
          git push
        else
          echo "No changes to commit."
        fi